[build]
  publish = "/"        # root folder contains index.html
  command = ""         # no build required for static HTML

[dev]
  command = "npx live-server --port=8888"
  port = 8888
  targetPort = 8888

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
